// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: grpc/pb/model.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pb_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_grpc_pb_model_proto_rawDescGZIP(), []int{0}
}

type OsInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Os   string `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch string `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
}

func (x *OsInfoRsp) Reset() {
	*x = OsInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pb_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OsInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OsInfoRsp) ProtoMessage() {}

func (x *OsInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OsInfoRsp.ProtoReflect.Descriptor instead.
func (*OsInfoRsp) Descriptor() ([]byte, []int) {
	return file_grpc_pb_model_proto_rawDescGZIP(), []int{1}
}

func (x *OsInfoRsp) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *OsInfoRsp) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type PidRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *PidRsp) Reset() {
	*x = PidRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pb_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PidRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PidRsp) ProtoMessage() {}

func (x *PidRsp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PidRsp.ProtoReflect.Descriptor instead.
func (*PidRsp) Descriptor() ([]byte, []int) {
	return file_grpc_pb_model_proto_rawDescGZIP(), []int{2}
}

func (x *PidRsp) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

var File_grpc_pb_model_proto protoreflect.FileDescriptor

var file_grpc_pb_model_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x2f, 0x0a, 0x09, 0x4f, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73,
	0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x61, 0x72, 0x63, 0x68, 0x22, 0x1a, 0x0a, 0x06, 0x50, 0x69, 0x64, 0x52, 0x73, 0x70, 0x12,
	0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69,
	0x64, 0x32, 0x59, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x4f, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x23, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x50, 0x69,
	0x64, 0x12, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a,
	0x2e, 0x70, 0x62, 0x2e, 0x50, 0x69, 0x64, 0x52, 0x73, 0x70, 0x22, 0x00, 0x42, 0x23, 0x5a, 0x21,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x61, 0x72, 0x73, 0x6b,
	0x79, 0x30, 0x30, 0x37, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_pb_model_proto_rawDescOnce sync.Once
	file_grpc_pb_model_proto_rawDescData = file_grpc_pb_model_proto_rawDesc
)

func file_grpc_pb_model_proto_rawDescGZIP() []byte {
	file_grpc_pb_model_proto_rawDescOnce.Do(func() {
		file_grpc_pb_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_pb_model_proto_rawDescData)
	})
	return file_grpc_pb_model_proto_rawDescData
}

var file_grpc_pb_model_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_pb_model_proto_goTypes = []interface{}{
	(*Request)(nil),   // 0: pb.Request
	(*OsInfoRsp)(nil), // 1: pb.OsInfoRsp
	(*PidRsp)(nil),    // 2: pb.PidRsp
}
var file_grpc_pb_model_proto_depIdxs = []int32{
	0, // 0: pb.Greeter.GetOsInfo:input_type -> pb.Request
	0, // 1: pb.Greeter.GetPid:input_type -> pb.Request
	1, // 2: pb.Greeter.GetOsInfo:output_type -> pb.OsInfoRsp
	2, // 3: pb.Greeter.GetPid:output_type -> pb.PidRsp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_pb_model_proto_init() }
func file_grpc_pb_model_proto_init() {
	if File_grpc_pb_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_pb_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_pb_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OsInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_pb_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PidRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_pb_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_pb_model_proto_goTypes,
		DependencyIndexes: file_grpc_pb_model_proto_depIdxs,
		MessageInfos:      file_grpc_pb_model_proto_msgTypes,
	}.Build()
	File_grpc_pb_model_proto = out.File
	file_grpc_pb_model_proto_rawDesc = nil
	file_grpc_pb_model_proto_goTypes = nil
	file_grpc_pb_model_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	GetOsInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*OsInfoRsp, error)
	GetPid(ctx context.Context, in *Request, opts ...grpc.CallOption) (*PidRsp, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) GetOsInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*OsInfoRsp, error) {
	out := new(OsInfoRsp)
	err := c.cc.Invoke(ctx, "/pb.Greeter/GetOsInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetPid(ctx context.Context, in *Request, opts ...grpc.CallOption) (*PidRsp, error) {
	out := new(PidRsp)
	err := c.cc.Invoke(ctx, "/pb.Greeter/GetPid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	GetOsInfo(context.Context, *Request) (*OsInfoRsp, error)
	GetPid(context.Context, *Request) (*PidRsp, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) GetOsInfo(context.Context, *Request) (*OsInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOsInfo not implemented")
}
func (*UnimplementedGreeterServer) GetPid(context.Context, *Request) (*PidRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPid not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_GetOsInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetOsInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Greeter/GetOsInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetOsInfo(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetPid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetPid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Greeter/GetPid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetPid(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOsInfo",
			Handler:    _Greeter_GetOsInfo_Handler,
		},
		{
			MethodName: "GetPid",
			Handler:    _Greeter_GetPid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/pb/model.proto",
}
